create table proffesion (
    id BIGSERIAL NOT NULL PRIMARY KEY,
    proffesion VARCHAR
);
 
create table additional_info (
    id BIGSERIAL NOT NULL PRIMARY KEY,
    additional_info VARCHAR
);
 
create table baggage (
    id BIGSERIAL NOT NULL PRIMARY KEY,
    baggage VARCHAR
);
 
create table bunker_data (
    id BIGSERIAL NOT NULL PRIMARY KEY,
    bunker_data VARCHAR
);
 
create table additional_card (
    id BIGSERIAL NOT NULL PRIMARY KEY,
    skill VARCHAR
);
 
create table character_info (
    id BIGSERIAL NOT NULL PRIMARY KEY,
    character VARCHAR
);
 
create table global_event (
    id BIGSERIAL NOT NULL PRIMARY KEY,
    global_event VARCHAR
);
 
create table health (
    id BIGSERIAL NOT NULL PRIMARY KEY,
    health VARCHAR
);
 
create table hobbies (
    id BIGSERIAL NOT NULL PRIMARY KEY,
    hobbies VARCHAR
);
 
create table phobia (
    id BIGSERIAL NOT NULL PRIMARY KEY,
    phobia VARCHAR
);
 
create table weight_data (
    id BIGSERIAL NOT NULL PRIMARY KEY,
    weight VARCHAR
);
 
insert into proffesion (proffesion) values ('Полицейский');
insert into proffesion (proffesion) values ('Стриптизер');
insert into proffesion (proffesion) values ('Слесарь');
insert into proffesion (proffesion) values ('Парикмахер');
insert into proffesion (proffesion) values ('Таксист');
insert into proffesion (proffesion) values ('Директор предприятия');
insert into proffesion (proffesion) values ('Учитель');
insert into proffesion (proffesion) values ('Рекрутер');
insert into proffesion (proffesion) values ('Аналитик');
insert into proffesion (proffesion) values ('Историк');
insert into proffesion (proffesion) values ('Переводчик');
insert into proffesion (proffesion) values ('Вирусолог');
insert into proffesion (proffesion) values ('Имиджмейкер');
insert into proffesion (proffesion) values ('Актер');
insert into proffesion (proffesion) values ('Ландшафтный дизайнер');
insert into proffesion (proffesion) values ('Блогер');
insert into proffesion (proffesion) values ('Хирург');
insert into proffesion (proffesion) values ('Ветеринар');
insert into proffesion (proffesion) values ('Эколог');
insert into proffesion (proffesion) values ('Маляр');
insert into proffesion (proffesion) values ('Судья');
insert into proffesion (proffesion) values ('Следователь');
insert into proffesion (proffesion) values ('Пожарный');
insert into proffesion (proffesion) values ('Кинолог ');
insert into proffesion (proffesion) values ('Гувернантка ');
insert into proffesion (proffesion) values ('Адвокат');
insert into proffesion (proffesion) values ('Дегустатор');
insert into proffesion (proffesion) values ('Шеф-повар');
insert into proffesion (proffesion) values ('Бармен');
insert into proffesion (proffesion) values ('Секретарь');
insert into proffesion (proffesion) values ('Курьер');
insert into proffesion (proffesion) values ('Дворецкий');
insert into proffesion (proffesion) values ('Страховой агент');
insert into proffesion (proffesion) values ('Электрик');
insert into proffesion (proffesion) values ('Психолог');
insert into proffesion (proffesion) values ('Продавец-консультант');
insert into proffesion (proffesion) values ('Автомеханик');
insert into proffesion (proffesion) values ('Агроном');
insert into proffesion (proffesion) values ('Экономист');
insert into proffesion (proffesion) values ('Брокер');
insert into proffesion (proffesion) values ('Налоговый инспектор');
insert into proffesion (proffesion) values ('Фитнес тренер');
insert into proffesion (proffesion) values ('Диджей');
insert into proffesion (proffesion) values ('Клоун');
insert into proffesion (proffesion) values ('Каскадер');
insert into proffesion (proffesion) values ('Продюссер');
insert into proffesion (proffesion) values ('Астрофизик');
insert into proffesion (proffesion) values ('Онколог ');
insert into proffesion (proffesion) values ('Фотограф');
insert into proffesion (proffesion) values ('Капитан специального назначения');
insert into proffesion (proffesion) values ('Адмирал (Военно-Морской Флот России)');
insert into proffesion (proffesion) values ('Кондуктор');
insert into proffesion (proffesion) values ('Президент Югославии');
insert into proffesion (proffesion) values ('Жигало ');
insert into proffesion (proffesion) values ('Космонавт');
insert into proffesion (proffesion) values ('Безработный');
insert into proffesion (proffesion) values ('Комик');
insert into proffesion (proffesion) values ('Инженер');
insert into proffesion (proffesion) values ('Дворецкий');
insert into proffesion (proffesion) values ('Архитектор');
insert into proffesion (proffesion) values ('Строитель');
insert into proffesion (proffesion) values ('Сексолог');
insert into proffesion (proffesion) values ('Учитель');
insert into proffesion (proffesion) values ('Депутат');
insert into proffesion (proffesion) values ('Физик ядерщик');
insert into proffesion (proffesion) values ('Астроном');
insert into proffesion (proffesion) values ('ВДВшник');
insert into proffesion (proffesion) values ('Порноактер');
insert into proffesion (proffesion) values ('Вебкам модель');
insert into proffesion (proffesion) values ('Инженер');
insert into additional_info (additional_info) values ('Является мастером спорта по боксу');
insert into additional_info (additional_info) values ('Имеет 2 высших образования');
insert into additional_info (additional_info) values ('Является резидентом Comedy Club');
insert into additional_info (additional_info) values ('Верит в пришельцев');
insert into additional_info (additional_info) values ('Хорошо знает высшую математику');
insert into additional_info (additional_info) values ('Умеет ориентироваться по звездам');
insert into additional_info (additional_info) values ('Может оказать первую помощь');
insert into additional_info (additional_info) values ('Проходил(а) курс по самообороне');
insert into additional_info (additional_info) values ('Проходил курсы по выживанию');
insert into additional_info (additional_info) values ('Знает наизусть все стихи Пушкина');
insert into additional_info (additional_info) values ('Читал(а) книгу про выживание на необитаемом острове');
insert into additional_info (additional_info) values ('Сидел(а) в тюрьме');
insert into additional_info (additional_info) values ('По первому образованию - терапевт');
insert into additional_info (additional_info) values ('Верит в сверхъестественных существ');
insert into additional_info (additional_info) values ('Спасал(а) утопающего');
insert into additional_info (additional_info) values ('Быстро бегает');
insert into additional_info (additional_info) values ('Побывал(а) в восемнадцати странах');
insert into additional_info (additional_info) values ('Разговаривает на 3 языках');
insert into additional_info (additional_info) values ('Умеет делать оружие из любой херни');
insert into additional_info (additional_info) values ('Ненавидит современную музыку');
insert into additional_info (additional_info) values ('Побывал(а) на вершине Эвереста');
insert into additional_info (additional_info) values ('Увлекается охотой');
insert into additional_info (additional_info) values ('Является копрофилом');
insert into additional_info (additional_info) values ('Ведёт личный дневник');
insert into additional_info (additional_info) values ('Гадает по картам');
insert into additional_info (additional_info) values ('Пережил(а) три покушения');
insert into additional_info (additional_info) values ('Продал(а) почку');
insert into additional_info (additional_info) values ('Может оказать первую помощь');
insert into additional_info (additional_info) values ('Был(а) вожатым в лагере');
insert into additional_info (additional_info) values ('Любит показывать карточные фокусы');
insert into additional_info (additional_info) values ('Верит в экстрасенсов');
insert into additional_info (additional_info) values ('Спасал(а) утопающего');
insert into additional_info (additional_info) values ('Ворует кошельки');
insert into additional_info (additional_info) values ('Страдает морской болезнью');
insert into additional_info (additional_info) values ('Проходил курсы сексолога');
insert into additional_info (additional_info) values ('Ограбил(а) банк');
insert into additional_info (additional_info) values ('Проходил(а) курсы кулинарии');
insert into additional_info (additional_info) values ('Умеет делать и чинить часы');
insert into additional_info (additional_info) values ('Любит мягкие игрушки');
insert into additional_info (additional_info) values ('Читал книги про зомби');
insert into additional_info (additional_info) values ('Думает что эта катастрофа - заговор рептилий');
insert into additional_info (additional_info) values ('Шулер');
insert into additional_info (additional_info) values ('Проходил(а) курсы массажа');
insert into additional_info (additional_info) values ('Думает что живет в матрице');
insert into additional_info (additional_info) values ('Владеет хорошей спортивной подготовкой');
insert into additional_info (additional_info) values ('Умеет вскрывать замки');
insert into additional_info (additional_info) values ('Умеет варить пиво');
insert into additional_info (additional_info) values ('Хорошо знает высшую математику');
insert into additional_info (additional_info) values ('Смотрел фильмы про апокалипсис');
insert into additional_info (additional_info) values ('Занял(а) первое место на марафоне');
insert into additional_info (additional_info) values ('Умеет стрелять');
insert into additional_info (additional_info) values ('Поставил(а) мировой рекорд по поеданию бургеров');
insert into additional_info (additional_info) values ('Хорошо ладит с животными');
insert into additional_info (additional_info) values ('IQ меньше 70');
insert into additional_info (additional_info) values ('IQ 150');
insert into additional_info (additional_info) values ('Входил в топ-100 богатейших людей в мире');
insert into additional_info (additional_info) values ('Осужден за педофилию');
insert into additional_info (additional_info) values ('Перфекционист');
insert into additional_info (additional_info) values ('Зоофил');
insert into additional_info (additional_info) values ('Феноменальная память');
insert into additional_info (additional_info) values ('Стратег');
insert into additional_info (additional_info) values ('Имеет суицидальные наклонности');
insert into additional_info (additional_info) values ('Имеет садистские наклонности');
insert into additional_info (additional_info) values ('Свингер');
insert into baggage (baggage) values ('Стерильные одноразовые шприцы');
insert into baggage (baggage) values ('Зажигалка');
insert into baggage (baggage) values ('Семена');
insert into baggage (baggage) values ('Четыре рации');
insert into baggage (baggage) values ('Компас');
insert into baggage (baggage) values ('Пистолет с одним патроном');
insert into baggage (baggage) values ('Кофе');
insert into baggage (baggage) values ('Комиксы');
insert into baggage (baggage) values ('Фильтр для воды');
insert into baggage (baggage) values ('Рулоны туалетной бумаги');
insert into baggage (baggage) values ('Стерильные одноразовые шприцы');
insert into baggage (baggage) values ('Три респираторные маски');
insert into baggage (baggage) values ('Консервы');
insert into baggage (baggage) values ('Аптечка');
insert into baggage (baggage) values ('Скрипка');
insert into baggage (baggage) values ('Попугай');
insert into baggage (baggage) values ('Коробка пазлов');
insert into baggage (baggage) values ('Грудной ребёнок');
insert into baggage (baggage) values ('Ноутбук');
insert into baggage (baggage) values ('Четыре рации');
insert into baggage (baggage) values ('Карманные часы');
insert into baggage (baggage) values ('Карты таро');
insert into baggage (baggage) values ('Коробка с боеприпасами');
insert into baggage (baggage) values ('Пачка сигарет');
insert into baggage (baggage) values ('Компьютер');
insert into baggage (baggage) values ('Запас шоколадок на две недели');
insert into baggage (baggage) values ('Лук и стрелы');
insert into baggage (baggage) values ('Плюшевый медведь');
insert into baggage (baggage) values ('Зажигалка');
insert into baggage (baggage) values ('Книга по социологии');
insert into baggage (baggage) values ('Набор инструментов');
insert into baggage (baggage) values ('Фильтр для воды');
insert into baggage (baggage) values ('Губная гармошка');
insert into baggage (baggage) values ('Семена');
insert into baggage (baggage) values ('Ящик пива');
insert into baggage (baggage) values ('Тесак');
insert into baggage (baggage) values ('1кг марихуаны');
insert into baggage (baggage) values ('Три респираторные маски');
insert into baggage (baggage) values ('Книга по социологии');
insert into baggage (baggage) values ('Настольные игры');
insert into baggage (baggage) values ('Топор и веревка');
insert into baggage (baggage) values ('Компас');
insert into baggage (baggage) values ('Бутылка водки');
insert into baggage (baggage) values ('200грамм кокса');
insert into baggage (baggage) values ('Золотые сережки');
insert into baggage (baggage) values ('Журнал с кроссвордами');
insert into baggage (baggage) values ('Пачка сигарет');
insert into baggage (baggage) values ('Фонарик и запасные батарейки');
insert into baggage (baggage) values ('Принтер');
insert into baggage (baggage) values ('Книга по выживанию');
insert into baggage (baggage) values (' Коробок спичек');
insert into baggage (baggage) values ('Попугай');
insert into baggage (baggage) values ('Настольные игры');
insert into baggage (baggage) values ('Фотоаппарат');
insert into baggage (baggage) values ('Книги');
insert into baggage (baggage) values ('Набор для шитья');
insert into baggage (baggage) values ('Газовая горелка');
insert into baggage (baggage) values ('Радиоуправляемая машинка');
insert into baggage (baggage) values ('Противогаз');
insert into baggage (baggage) values ('Собака');
insert into baggage (baggage) values ('Пистолет с одним патроном');
insert into baggage (baggage) values ('Дедовское ружьё');
insert into baggage (baggage) values ('Сотовый телефон');
insert into baggage (baggage) values ('Десять одноразовых медицинских масок');
insert into baggage (baggage) values ('Пачка презервативов');
insert into baggage (baggage) values ('Коробка с боеприпасами');
insert into baggage (baggage) values ('Ребенок 12 лет');
insert into baggage (baggage) values ('Кошка');
insert into baggage (baggage) values ('Набор кухонных приборов');
insert into baggage (baggage) values ('Мясо');
insert into baggage (baggage) values ('Семена пшеницы');
insert into baggage (baggage) values ('Кофе');
insert into baggage (baggage) values ('Только что использованый презерватив');
insert into baggage (baggage) values ('Воображаемый друг');
insert into baggage (baggage) values ('Стрелы');
insert into bunker_data (bunker_data) values ('Кухня');
insert into bunker_data (bunker_data) values ('Медпункт с большим набором лекарств');
insert into bunker_data (bunker_data) values ('Столовая');
insert into bunker_data (bunker_data) values ('Комната для массажа');
insert into bunker_data (bunker_data) values ('Детская комната');
insert into bunker_data (bunker_data) values ('Склад с едой');
insert into bunker_data (bunker_data) values ('Склад с медикаментами');
insert into bunker_data (bunker_data) values ('Операционная');
insert into bunker_data (bunker_data) values ('Тренажерный зал');
insert into bunker_data (bunker_data) values ('Звукозаписывающая студия');
insert into bunker_data (bunker_data) values ('Комната для пыток');
insert into bunker_data (bunker_data) values ('Винный погреб');
insert into bunker_data (bunker_data) values ('Порно студия');
insert into bunker_data (bunker_data) values ('Библиотека со всеми обучающими книгами в мире');
insert into bunker_data (bunker_data) values ('Комната с супер мощным телескопом (самая важная часть бункера)');
insert into bunker_data (bunker_data) values ('Оружейная');
insert into bunker_data (bunker_data) values ('Теплица');
insert into bunker_data (bunker_data) values ('Рассадник');
insert into bunker_data (bunker_data) values ('Ящик с оружием');
insert into bunker_data (bunker_data) values ('Ящик с патронами');
insert into bunker_data (bunker_data) values ('Набор инструментов');
insert into bunker_data (bunker_data) values ('Материалы для строительства');
insert into bunker_data (bunker_data) values ('Граната');
insert into bunker_data (bunker_data) values ('Кофемашина');
insert into bunker_data (bunker_data) values ('Гитара ');
insert into bunker_data (bunker_data) values ('Барабаны');
insert into bunker_data (bunker_data) values ('Книжная полка с детскими книжками');
insert into bunker_data (bunker_data) values ('Книжная полка с литературой про зомби');
insert into bunker_data (bunker_data) values ('Книжная полка с научной литературой');
insert into bunker_data (bunker_data) values ('Книжная полка с порно журналами');
insert into bunker_data (bunker_data) values ('Книги по психологии');
insert into bunker_data (bunker_data) values ('Сборник журналов ');
insert into bunker_data (bunker_data) values ('Сделай сам');
insert into bunker_data (bunker_data) values ('Полка с настольными играми');
insert into bunker_data (bunker_data) values ('Осцилограф');
insert into bunker_data (bunker_data) values ('Пара прожекторов');
insert into bunker_data (bunker_data) values ('Детские игрушки');
insert into bunker_data (bunker_data) values ('Пара автоматов');
insert into bunker_data (bunker_data) values ('Пара самурайских мечей');
insert into bunker_data (bunker_data) values ('Рекурсивный лук');
insert into additional_card (additional_card) values ('Указаный тобой игрок раскрывает любую характеристику по вашему выбору');
insert into additional_card (additional_card) values ('В 20 м от бункера есть склад с оружием');
insert into additional_card (additional_card) values ('В 100 м от вас есть бункер с мужчинами(Здоровыми и Плодовитыми)');
insert into additional_card (additional_card) values ('Данная карта даёт вам возможность поменять способность к деторождению любого игрока на противоположный');
insert into additional_card (additional_card) values ('Указаный тобой игрок раскрывает одну характеристику по вашему выбору');
insert into additional_card (additional_card) values ('В 30 м от бункера есть погреб с вином');
insert into additional_card (additional_card) values ('Указаный тобой игрок раскрывает свое здоровье');
insert into additional_card (additional_card) values ('В 50 м от вас есть бункер с женщинами(С возмощностью производства наследия 3 раза, после они умирают (господи зачем так сложно???))');
insert into additional_card (additional_card) values ('Поблизости находится агресивно настроенный бункер (ну очень агрессивно настроеный бункер)');
insert into additional_card (additional_card) values ('Вы можете активировать карту №2 указаного тобой игрока по выбору');
insert into additional_card (additional_card) values ('Указаный тобой игрок раскрывает одну характеристику по вашему выбору');
insert into additional_card (additional_card) values ('Ваш бункер находится около пресного озера');
insert into additional_card (additional_card) values ('Вы можете активировать карту №1 указаного тобой игрока по выбору');
insert into additional_card (additional_card) values ('Защищает любого игрока на один ход(кроме вас)');
insert into additional_card (additional_card) values ('Лечит любого игрока, включая вас');
insert into additional_card (additional_card) values ('Аннулирование всех профессий');
insert into additional_card (additional_card) values ('НЕОЖИДАННЫЙ ПОВОРOТ (поблизости есть еще один бункер 300м.кв. с набором первой мед помощи, телевизором и всемя частями Американского пирога');
insert into additional_card (additional_card) values ('При равном количестве голосов на вылет, ты остаешься в игре, противник вылетает (разыгрывать в саааааааамый последний момент =))');
insert into additional_card (additional_card) values ('Аннулирование всех профессий');
insert into additional_card (additional_card) values ('Заткни противника (запрещено разговаривать на обсуждении)');
insert into additional_card (additional_card) values ('На територии бункера находиться зоопарк (вот и нахер он нам нужен?)');
insert into additional_card (additional_card) values ('Указаный тобой игрок раскрывает любую характеристику ');
insert into additional_card (additional_card) values ('Указаный тобой игрок раскрывает одну характеристику по вашему выбору');
insert into additional_card (additional_card) values ('В бункере нету света');
insert into additional_card (additional_card) values ('Присваивает выбранному игроку еще одну рандомную фобию');
insert into additional_card (additional_card) values ('Замена хобби из колоды ');
insert into additional_card (additional_card) values ('замена телосложения из колоды');
insert into additional_card (additional_card) values ('замена возраста с колоды');
insert into additional_card (additional_card) values ('обмена возрастом с любым игроком');
insert into additional_card (additional_card) values ('обмен телосложения с любым игроком');
insert into additional_card (additional_card) values ('В 1000 м от вас есть бункер с мужчинами(Здоровыми и Плодовитыми)');
insert into additional_card (additional_card) values ('В 3км от вас есть бункер с мужчинами(Не здоровыми, но Плодовитыми)');
insert into additional_card (additional_card) values ('В 100 м от вас есть бункер с мужчинами(Здоровыми и Плодовитыми)');
insert into additional_card (additional_card) values ('В 10км от вас есть бункер с женщинами(Здоровыми и Плодовитыми)');
insert into additional_card (additional_card) values ('В 150 м от вас есть бункер с женщинами(Не здоровыми, но Плодовитыми)');
insert into additional_card (additional_card) values ('В 700 м от вас есть бункер с женщинами(Здоровыми и Плодовитыми)');
insert into additional_card (additional_card) values ('Данная карта даёт вам возможность поменять способность к деторождению любого игрока на противоположный');
insert into additional_card (additional_card) values ('Иммунитет на голосовании, на следующем кругу нужно выгнать двоих');
insert into additional_card (additional_card) values ('НЕОЖИДАННЫЙ ПОВОРOТ (у тебя украли багаж, теперь ты можешь украсть чужой)');
insert into additional_card (additional_card) values ('Укради чужой багаж (плохой поступок, но кому не похер?)');
insert into additional_card (additional_card) values ('Все узнают что поблизости находится заброшенная аптека');
insert into additional_card (additional_card) values ('Позволяет вам скрыть любую одну характеристику и не рассказывать о ней');
insert into additional_card (additional_card) values ('Все узнают что рядом есть бункер с двумя молодыми женщинами-медиками 30 лет');
insert into additional_card (additional_card) values ('Изменить свой багаж на новый');
insert into additional_card (additional_card) values ('Ваш голос считается за два ');
insert into additional_card (additional_card) values ('Вернуть игрока в бункер');
insert into additional_card (additional_card) values ('Поменяться хобби с другим игроком');
insert into additional_card (additional_card) values ('Обмен профессиями слева направо');
insert into additional_card (additional_card) values ('Вы можете заставить игрока замолчать на голосовании');
insert into additional_card (additional_card) values ('Ты можешь обменять свою фобию на фобию другого игрока');
insert into additional_card (additional_card) values ('Поменяться багажом с другим игроком');
insert into additional_card (additional_card) values ('Вернуть игрока в игру');
insert into additional_card (additional_card) values ('Убирает одно место в бункере');
insert into additional_card (additional_card) values ('Обмен профессиями справа налево');
insert into additional_card (additional_card) values ('Ты можешь поменять свою карту фобии на новую');
insert into additional_card (additional_card) values ('Друг(Игрок после тебя обязательно должен попасть в бункер)');
insert into additional_card (additional_card) values ('Друг(Игрок перед тобой обязательно должен попасть в бункер)');
insert into additional_card (additional_card) values ('Ты можешь поменять свою карту профессии на новую из колоды');
insert into additional_card (additional_card) values ('Добавляет одно место в бункере');
insert into additional_card (additional_card) values ('Враг(Игрок перед тобой не должен попасть в бункер)');
insert into additional_card (additional_card) values ('У тебя есть защита на 1 игровой круг (Если против твоего персонажа максимальное кол-во голосов)');
insert into additional_card (additional_card) values ('НЕОЖИДАННЫЙ ПОВОРТ (каждый персонаж должен разыграть одну из карт действий)');
insert into additional_card (additional_card) values ('Вы можете перекинуть чужой голос на другого игрока');
insert into additional_card (additional_card) values ('Враг(Игрок после тебя не должен попасть в бункер)');
insert into additional_card (additional_card) values ('Убирает одно место в бункере');
insert into additional_card (additional_card) values ('НЕОЖИДАННЫЙ ПОВОРТ (анулирует чужую карту действия)');
insert into additional_card (additional_card) values ('Добавляет одно место в бункере');
insert into additional_card (additional_card) values ('Поменяться здоровьем с другим игроком');
insert into additional_card (additional_card) values ('Поменяться багажом с другим игроком');
insert into additional_card (additional_card) values ('Поменяться доп инфой с другим игроком');
insert into additional_card (additional_card) values ('Замена всех професий');
insert into additional_card (additional_card) values ('Замена возраста для всех');
insert into additional_card (additional_card) values ('Замена здоровья для всех');
insert into additional_card (additional_card) values ('Замена всех фобий из колоды');
insert into character_info (character_info) values ('Вспыльчивый');
insert into character_info (character_info) values ('Обидчивый');
insert into character_info (character_info) values ('Понимающий');
insert into character_info (character_info) values ('Равнодушный');
insert into character_info (character_info) values ('Лицемерный');
insert into character_info (character_info) values ('Честный');
insert into character_info (character_info) values ('Грубый');
insert into character_info (character_info) values ('Мелочный');
insert into character_info (character_info) values ('Понимающий');
insert into character_info (character_info) values ('Гнусный');
insert into character_info (character_info) values ('Бесстрашный');
insert into character_info (character_info) values ('Грамотный');
insert into character_info (character_info) values ('Доверчивый');
insert into character_info (character_info) values ('Обидчивый');
insert into character_info (character_info) values ('Вежливость');
insert into character_info (character_info) values ('Алчный');
insert into character_info (character_info) values ('Образованный');
insert into character_info (character_info) values ('Деспотичный');
insert into character_info (character_info) values ('Неграмотный');
insert into character_info (character_info) values ('Вредный');
insert into character_info (character_info) values ('Яростный');
insert into character_info (character_info) values ('Болтливый');
insert into character_info (character_info) values ('Гордый');
insert into character_info (character_info) values ('Брезгливый');
insert into character_info (character_info) values ('Депрессивный');
insert into character_info (character_info) values ('Бесстыдный');
insert into character_info (character_info) values ('Навязчивый');
insert into character_info (character_info) values ('Коварный');
insert into character_info (character_info) values ('Заботливый');
insert into character_info (character_info) values ('Закрытый');
insert into character_info (character_info) values ('Душевный');
insert into character_info (character_info) values ('Аскетизм');
insert into character_info (character_info) values ('Капризный');
insert into character_info (character_info) values ('Доверчивый');
insert into character_info (character_info) values ('Высокомерие');
insert into character_info (character_info) values ('Герой');
insert into character_info (character_info) values ('Настойчивый');
insert into character_info (character_info) values ('Двуличный');
insert into character_info (character_info) values ('Искренный');
insert into character_info (character_info) values ('Жалкий');
insert into character_info (character_info) values ('Жестокий');
insert into character_info (character_info) values ('Бережливый');
insert into character_info (character_info) values ('Великодушный');
insert into character_info (character_info) values ('Агрессивный');
insert into character_info (character_info) values ('Смешной');
insert into character_info (character_info) values ('Болтливый');
insert into character_info (character_info) values ('Гуманный');
insert into character_info (character_info) values ('Властный');
insert into character_info (character_info) values ('Безумный');
insert into character_info (character_info) values ('Ленивый');
insert into character_info (character_info) values ('Жадный');
insert into character_info (character_info) values ('Тихий');
insert into character_info (character_info) values ('Добрый');
insert into character_info (character_info) values ('Стевозный');
insert into character_info (character_info) values ('Раздражительний');
insert into character_info (character_info) values ('Искустный пьяница');
insert into global_event (global_event) values ('Закончилась третяя, ядерная, мировая война, по крайней мере в это хочется верить, так как уничтожено 99.9% населения земли, оставшиеся люди успели укрыться в бункерах, что придется сделать и нам. Облака пепла закрыли небо на долгие годы( ядерная зима) все растения и животные погибли. Время ожидания в бункере - 20 лет');
insert into global_event (global_event) values ('Мир в анархии, массовые терракты по всему миру. Взрыв на химическом заводе в атмосферу попало много ядовитых паров, заражена земля и вода. К счастью в нашем небольшом городке был бункер времён холодной войны, где можно переждать. Остаток населения Земли 5 миллионов человек у которых иммунитетом к яду. Нахождение в бункере - 3 года (пока ядовитый газ не изчезнет)');
insert into global_event (global_event) values ('Классический зомби апокалипсис как в фильмах, армия не справляется с толпами заражённых. Единственный способ группе выживших спастись, это переждать в бункере как минимум 20 лет, пока все на поверхности не умрут.');
insert into global_event (global_event) values ('Произошел глобальный потоп, в следствии чего население земли сократилось до 2 миллионов человек, осталось только 15% суши, изменился кардинально климат, на тропический, нужно будет привыкать к новым растениям и животным (крупные растения и насекомые). Срок пробывания в бункере 2 года.');
insert into global_event (global_event) values ('Химическая война. В результате применения химического и бактериологического оружия был нарушен микробиологический состав почв значительно изменился экологический баланс растения почва и вода были отравлены. На Земле остался малый процент населяющих её живых существ. Остаток выжившего населения: 1% ');
insert into global_event (global_event) values ('Инопланетная раса решила захватить Землю Межпланетные аппараты падают на поверхность планеты один за другим Оружие военных оказывается бессильным против них и постепенно пришельцы истребляют большую часть населения После выхода из бункера подавляющее большинство инопланетян погибло из-за неприспособленности к микроорганизмами населяющими Землю Остаток выжившего населения: 1% ');
insert into global_event (global_event) values ('Суперкомпьютер. Искусственный интеллект который задумывался для управления системами обороны вышел из строя и посчитал человечество большой опасностью. Это привело к тому что искусственный интеллект отключил инструкцию не убивать человека и взял под контроль процедуры управления военными роботами которые начали истреблять человечество. Суперкомпьютер захватил власть над планетой выжившим людям пришлось прятаться в старых бункерах. Остаток выжившего населения: 4%');
insert into global_event (global_event) values ('На планету падает космический объект огромных размеров создавая мощную ударную волну которая сносит все на своем пути. На месте падения образовывается масштабный кратер. Повсюду проходят сильные землетрясения и цунами. Пожары охватывают всю Землю а из-за количество пыли которое поднялось в атмосферу на планете настает долгая ядерная зима. Остаток выжившего населения: 30% ');
insert into global_event (global_event) values ('Проект «A.N. USA» Военные работавшие над проектом нечаянно открыли вход в иное измерение. Густой неестественный белый туман медленно начал заполонять огромные участки поверхности Видимость практически нулевая. По миру стали бродить неведомые чудовища которые могут уничтожить все человечество. Разрушения глобальные. Остаток выжившего населения: 0,1%');
insert into global_event (global_event) values ('Взрыв Йеллоустонского супервулкана пошатнул Землю выброшенный в атмосферу пепел закрыл Солнце на несколько месяцев. На планете началась ядерная зима средняя температура опустилась на 11 градусов погибли пять из каждых шести населявших Землю существ Климат существенно изменился. На планете теперь царит глобальная засуха ');
insert into health (health) values ('Плоскостопие');
insert into health (health) values ('Слепота');
insert into health (health) values ('Сифилис');
insert into health (health) values ('Болезнь Альцгеймера');
insert into health (health) values ('Астма');
insert into health (health) values ('Депрессия');
insert into health (health) values ('Астма');
insert into health (health) values ('Диарея');
insert into health (health) values ('Сахарный диабет');
insert into health (health) values ('Глухой');
insert into health (health) values ('Нет ног');
insert into health (health) values ('Эпилепсия');
insert into health (health) values ('Шизофрения ');
insert into health (health) values ('Глухо-немой');
insert into health (health) values ('Заикание');
insert into health (health) values ('Аллергия на лекарства');
insert into health (health) values ('Сифилис');
insert into health (health) values ('Туберкулез');
insert into health (health) values ('Без руки');
insert into health (health) values ('Диабет');
insert into health (health) values ('Гастрит');
insert into health (health) values ('Биполярка');
insert into health (health) values ('СПИД ');
insert into health (health) values ('СПИД');
insert into health (health) values ('Язва желудка');
insert into health (health) values ('Без руки');
insert into health (health) values ('Несвертываемость крови');
insert into health (health) values ('Мигрени');
insert into health (health) values ('Кластерные головные боли');
insert into health (health) values ('Рак');
insert into health (health) values ('Слепота');
insert into health (health) values ('Бесплодие');
insert into health (health) values ('Бесплодие');
insert into health (health) values ('Кариес');
insert into health (health) values ('Бессонница');
insert into health (health) values ('Бессонница');
insert into health (health) values ('Бронхит');
insert into health (health) values ('Аллергия на шерсть');
insert into health (health) values ('Немой');
insert into health (health) values ('Рак');
insert into health (health) values ('Паранойя');
insert into health (health) values ('Косоглазие');
insert into health (health) values ('Дальтонизм');
insert into health (health) values ('ВИЧ ');
insert into health (health) values ('Плоскостопие');
insert into health (health) values ('Полностью здоровый');
insert into health (health) values ('Без ногтя');
insert into health (health) values ('Без пальца');
insert into health (health) values ('Без пальца ноги');
insert into health (health) values ('Здоров');
insert into health (health) values ('Бешенство');
insert into health (health) values ('Деменция');
insert into hobbies (hobbies) values ('Бодибилдинг');
insert into hobbies (hobbies) values ('Пение');
insert into hobbies (hobbies) values ('Верховая езда');
insert into hobbies (hobbies) values ('Рыбалка');
insert into hobbies (hobbies) values ('Виноделие');
insert into hobbies (hobbies) values ('Скалолазание');
insert into hobbies (hobbies) values ('Теннис');
insert into hobbies (hobbies) values ('Бег');
insert into hobbies (hobbies) values ('Взламывание замков');
insert into hobbies (hobbies) values ('Резьба по дереву');
insert into hobbies (hobbies) values ('Нумизматика');
insert into hobbies (hobbies) values ('Чтение');
insert into hobbies (hobbies) values ('Шахматы');
insert into hobbies (hobbies) values ('Фитнес');
insert into hobbies (hobbies) values ('Восточные танцы');
insert into hobbies (hobbies) values ('Катание на велосипеде');
insert into hobbies (hobbies) values ('Игра на гитаре');
insert into hobbies (hobbies) values ('Хиромантия');
insert into hobbies (hobbies) values ('Плавание');
insert into hobbies (hobbies) values ('Готовка');
insert into hobbies (hobbies) values ('Рукоделие');
insert into hobbies (hobbies) values ('Стриптиз');
insert into hobbies (hobbies) values ('Лыжи');
insert into hobbies (hobbies) values ('Верховая езда');
insert into hobbies (hobbies) values ('Боевые искусства');
insert into hobbies (hobbies) values ('Восточные танцы');
insert into hobbies (hobbies) values ('Будущий киберспортсмен (задрот)');
insert into hobbies (hobbies) values ('Стрельба');
insert into hobbies (hobbies) values ('Собирание пазлов');
insert into hobbies (hobbies) values ('Резьба по дереву');
insert into hobbies (hobbies) values ('Футбол');
insert into hobbies (hobbies) values ('Танцы');
insert into hobbies (hobbies) values ('Хиромантия');
insert into hobbies (hobbies) values ('Блоггерство');
insert into hobbies (hobbies) values ('Рыбалка');
insert into hobbies (hobbies) values ('Дартс');
insert into hobbies (hobbies) values ('Граффити');
insert into hobbies (hobbies) values ('Паркур');
insert into hobbies (hobbies) values ('Бильярд');
insert into hobbies (hobbies) values ('Готовка');
insert into hobbies (hobbies) values ('Зоология');
insert into hobbies (hobbies) values ('Любит собирать грибы');
insert into hobbies (hobbies) values ('Виноделие');
insert into hobbies (hobbies) values ('Резьба по металлу');
insert into hobbies (hobbies) values ('Садоводство');
insert into hobbies (hobbies) values ('Плавание');
insert into hobbies (hobbies) values ('Пикап');
insert into hobbies (hobbies) values ('Программирование');
insert into hobbies (hobbies) values ('Психология');
insert into hobbies (hobbies) values ('Татуировки и пирсинг');
insert into hobbies (hobbies) values ('Йога');
insert into hobbies (hobbies) values ('Алкоголизм');
insert into hobbies (hobbies) values ('Эксгибиционизм');
insert into hobbies (hobbies) values ('Умеет выживать в дикой природе');
insert into hobbies (hobbies) values ('Серфинг');
insert into hobbies (hobbies) values ('Фокусы');
insert into hobbies (hobbies) values ('Футбол');
insert into hobbies (hobbies) values ('Поход');
insert into hobbies (hobbies) values ('Сурвивализм');
insert into hobbies (hobbies) values ('Боевые искусства');
insert into hobbies (hobbies) values ('Метание ножей');
insert into hobbies (hobbies) values ('Езда на мотоцикле');
insert into hobbies (hobbies) values ('Сомелье');
insert into hobbies (hobbies) values ('Охота');
insert into hobbies (hobbies) values ('Историческая реконструкция');
insert into hobbies (hobbies) values ('Волонтёрство');
insert into phobia (phobia) values ('Вестифобия (Боязнь одеваться)');
insert into phobia (phobia) values ('Блаттофобия (Страх при виде тараканов/жуков)');
insert into phobia (phobia) values ('Гоплофобия (Боязнь при виде огнестрельного оружия)');
insert into phobia (phobia) values ('Гаптофобия (Боязнь касаний)');
insert into phobia (phobia) values ('Никрофобия (Боязнь темноты)');
insert into phobia (phobia) values ('Птеронофобия (Боязнь птичьих перьев)');
insert into phobia (phobia) values ('Нет фобий');
insert into phobia (phobia) values ('Аблутофобия (Боится плавать)');
insert into phobia (phobia) values ('Барофобия (Боязнь поднимать тяжести)');
insert into phobia (phobia) values ('Пирофобия – боязнь огня');
insert into phobia (phobia) values ('Виккафобия (Боязнь колдовства)');
insert into phobia (phobia) values ('Вагинофобия (Страх перед женскими гениталиями)');
insert into phobia (phobia) values ('Нет фобий');
insert into phobia (phobia) values ('Антофобия (Боязнь цветов)');
insert into phobia (phobia) values ('Нумерофобия (Боязнь чисел)');
insert into phobia (phobia) values ('Нет фобий');
insert into phobia (phobia) values ('Вагинофобия (Страх перед женскими гениталиями)');
insert into phobia (phobia) values ('Гравидофобия (Боязнь беременности)');
insert into phobia (phobia) values ('Эремофобия – боязнь одиночества');
insert into phobia (phobia) values ('Андрофобия (Боязнь мужчин и полового акта с ними)');
insert into phobia (phobia) values ('Айхмофобия – боязнь острых предметов');
insert into phobia (phobia) values ('Реектофобия – боязнь отказа');
insert into phobia (phobia) values ('Ахлуофобия – боязнь темноты');
insert into phobia (phobia) values ('Некрофобия – боязнь трупов');
insert into phobia (phobia) values ('Барофобия (Боязнь поднимать тяжести)');
insert into phobia (phobia) values ('Нет фобий');
insert into phobia (phobia) values ('Социофобия');
insert into phobia (phobia) values ('Кинофобия (Боязнь собак)');
insert into phobia (phobia) values ('X‑ФОБИЯ – боязнь буквы X');
insert into phobia (phobia) values ('Инсектофобия (Боязнь и страх всех насекомых)');
insert into phobia (phobia) values ('Блаттофобия (Страх при виде тараканов/жуков)');
insert into phobia (phobia) values ('Атихифобия – боязнь неудачи');
insert into phobia (phobia) values ('Анирофобия (Паникует во время перехода через улицу)');
insert into phobia (phobia) values ('Гоплофобия (Боязнь при виде огнестрельного оружия)');
insert into phobia (phobia) values ('Социофобия');
insert into phobia (phobia) values ('АНТРОПОФОБИЯ – боязнь людей');
insert into phobia (phobia) values ('ГИМНОФОБИЯ – боязнь наготы');
insert into phobia (phobia) values ('Гоплофобия (Боязнь при виде огнестрельного оружия)');
insert into phobia (phobia) values ('Алгофобия (Паника при боли)');
insert into phobia (phobia) values ('АНУПТАФОБИЯ – боязнь холостого образа жизни');
insert into phobia (phobia) values ('Вагинофобия (Страх перед женскими гениталиями)');
insert into phobia (phobia) values ('Нумерофобия (Боязнь чисел)');
insert into phobia (phobia) values ('Фелинофобия – боязнь кошек');
insert into phobia (phobia) values ('АутоМизофобия (Боязнь испачкаться)');
insert into phobia (phobia) values ('Мониторофобия – боязнь наблюдения');
insert into phobia (phobia) values ('Ятрофобия – боязнь врачей');
insert into phobia (phobia) values ('Вестифобия (Боязнь одеваться)');
insert into phobia (phobia) values ('Мелофобия (Боязнь музыки) Мизофобия (Боязнь грязи и микробов)');
insert into phobia (phobia) values ('Рипофобия – боязнь грязи');
insert into phobia (phobia) values ('Спермофобия – боязнь микробов');
insert into phobia (phobia) values ('АРКТОФОБИЯ – боязнь плюшевых мишек');
insert into phobia (phobia) values ('ГИНЕФОБИЯ – боязнь женщин');
insert into phobia (phobia) values ('ГОПЛОФОБИЯ – боязнь огнестрельного оружия');
insert into phobia (phobia) values ('ЗООФОБИЯ – боязнь животных (домашних)');
insert into phobia (phobia) values ('ИНФЕРТИЛИОФОБИЯ – боязнь бесплодия');
insert into phobia (phobia) values ('КАТАРАКТОФОБИЯ – боязнь катаракты');
insert into phobia (phobia) values ('КИМОФОБИЯ – боязнь волн');
insert into phobia (phobia) values ('ЛЕОНТОФОБИЯ – боязнь львов');
insert into phobia (phobia) values ('ЛАТЕКСОФОБИЯ – боязнь латекса');
insert into phobia (phobia) values ('МАММАФОБИЯ – боязнь груди');
insert into phobia (phobia) values ('МУСОФОБИЯ – боязнь мышей');
insert into phobia (phobia) values ('НЕГРОФОБИЯ – боязнь чернокожих людей');
insert into phobia (phobia) values ('ЭВРОТОФОБИЯ – боязнь влагалища');
insert into phobia (phobia) values ('ЭНТОМОФОБИЯ – боязнь насекомых');
insert into phobia (phobia) values ('ЭККЛЕСИОФОБИЯ – боязнь церквей');
insert into weight_data (weight_data) values ('Анорексия');
insert into weight_data (weight_data) values ('Ожирение (1 степень)');
insert into weight_data (weight_data) values ('Дефицит веса');
insert into weight_data (weight_data) values ('Норма');
insert into weight_data (weight_data) values ('Спортивное');
insert into weight_data (weight_data) values ('Накачаное');
insert into weight_data (weight_data) values ('Перекачанное');
insert into weight_data (weight_data) values ('Ожирение (2 степень)');